- name: Configure local JBoss Data Virtualization with HDP Hive JDBC driver 
  hosts: localhost
  connection: local
  tasks: 
    - name: Create JBoss module directory for the HDP Hive2 driver
      file: path="{{ jboss_home }}/modules/system/layers/dv/org/apache/hadoop/hive2/main" state=directory
    - name: Download HDP Hive JDBC jars
      get_url:
        url: "{{ item }}"
        dest: "{{ jboss_home }}/modules/system/layers/dv/org/apache/hadoop/hive2/main"
      with_items:
        - "{{ hadoop_auth_url }}"
        - "{{ hadoop_common_url }}"
        - "{{ hadoop_jdbc_standalone_url }}"
    - name: Copy module.xml into {{ jboss_home }}
      copy: 
        src: "{{ xml_dir }}/module.xml"
        dest: "{{ jboss_home }}/modules/system/layers/dv/org/apache/hadoop/hive2/main"
    - name: "Execute Management CLI file(s)"
      shell: 'bash -c "nohup {{ jboss_home }}/bin/standalone.sh -c {{ jboss_eap_instance_standalone_file }} -Djboss.socket.binding.port-offset={{ jboss_eap_instance_port_offset }} -Djboss.management.native.port={{ jboss_eap_instance_cli_default_port }} -Djboss.server.base.dir={{ jboss_eap_instance_dir }} --admin-only & " && sleep 10 && {{ jboss_home }}/bin/jboss-cli.sh -c --controller=127.0.0.1:{{ jboss_eap_instance_cli_port }} --file="{{ cli_dir }}/{{ item | basename }}" && pkill -TERM -f "java(.*){{ jboss_eap_instance_dir }}"'
      with_items: "{{ cli_list }}"
      ignore_errors: no
      register: cli_result
    
      


