install_home: "/Users/cvanball/test"
# =========== JBoss Data Virtualiation variables ===========
jboss_home: "{{ install_home }}/jboss-dv-6.3.0"

# Directory for the target running instance
jboss_eap_instance_dir: "{{ jboss_home }}/standalone"

# Name of the used standalone XML file
jboss_eap_instance_standalone_file: standalone.xml

# Port offset for the JBoss EAP instance
jboss_eap_instance_port_offset: 0

# Port used only during updates using the CLI (port should be available)
jboss_eap_instance_cli_default_port: 9999

# Offsetted port used for CLI updates
jboss_eap_instance_cli_port: "{{ jboss_eap_instance_cli_default_port|int + jboss_eap_instance_port_offset|int }}"

# =========== Other ===========
# Local directory containing the used CLI files
cli_dir: "{{ playbook_dir }}/files/cli"
xml_dir: "{{ playbook_dir }}/files/xml"
jdv_cli_list: { "configure_jdv.cli" }

# =========== JBoss Data Grid variables ===========
jdg_home: "{{ install_home }}/jboss-datagrid-6.6.0-server"

# Directory for the target running instance
jdg_instance_dir: "{{ jdg_home }}/standalone"

# Name of the used standalone XML file
jdg_instance_standalone_file: standalone.xml

# Port offset for the JBoss EAP instance
jdg_instance_port_offset: 100

# Port used only during updates using the CLI (port should be available)
jdg_instance_cli_default_port: 9999

# Offsetted port used for CLI updates
jdg_instance_cli_port: "{{ jdg_instance_cli_default_port|int + jdg_instance_port_offset|int }}"

# =========== Other ===========
# Local directory containing the used CLI files
jdg_cli_list: { "configure_jdg.cli" }
cli_timeout: 25